sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master

deploy:
  provider: heroku
  app: todo-checklist-react
  api_key:
    secure: "R2foDeQHGOTSiVVBUp0Lmjq8tgkg41LNPifPGHXHsiOLx8KVVATDAVzMgvfdIJN0RyHMvdthdo5earvXMQ1ug0GzT+aS07MGitLKnmXuL83jq+idwiRbeQQhohNxXKTl61aYDeVyGSInhR5A4EWTn3w38aovuFPtjYfZQi9Nv60="