sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
install:
- npm install
deploy:
  provider: heroku
  app: todo-checklist-react
  api_key:
    secure: o0PFnJZFvfo3aM/IitCxe/kt3419XMaPyneSrWQ2vDT/VYmEwbcUSWfni0vRY2twkCWRNQGnRzvlXdcALc2upx8VkEDA497AnNxTBrbVEsTAnzJP2B6fiB2wEXUjjGaT1/HUYx21j+8pLeDxsOCCFv3FSpNzvWCXwfGQ2Oc1r1KEFWTgycYZ6oU+hboTKkgXnKiA6ZX4tJTI2PBdllkWugqqQos/J8jfdbQOkQDUmcDW0dbBIQgU5+VwAn9gIWBIk9O6W3txZQ/woYSqaj3e9D0OdmaQkNtr5QWSC6iyoNqzQ3gDObwMEWOk6B4PD/oYC1khvSsZxgKZ0pG7SQzmYn2OVxF8do12LNBP7RzpIxSjFtxP+G/LbYHFdi1X0tbH7pwSyBtclOUITlsPQennFQ/7+26d1NMDweVxYupkv1zNl7xft8iU5bZprM6RLObMC3jRR+cyY5xrNLcPRV1DgajJIN1a6SCo+sz66VwFNqaI9sAWhf47ms7ssSi0VDmQV3pAWw1oOezwqGClIAa5RyQn2EmRuZn2NJUJeLlPn13taVdljfyE18q+iX+c0/cXhaKH72ZAPBElnq3Yi9x/pgCOZi7ig3Akh1RZ8Awq6P2WkJTsXAkCkYBllA77Ld/a2501Z2F8QvAvmVjLwVy9aeZwDh36HD87duEqnjes8Mk=
